# Generated by Django 2.1.7 on 2019-10-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('isbn', models.CharField(default='1E1E', max_length=50)),
                ('thumbnail', models.CharField(default='https://SOME STRING', max_length=150)),
                ('category', models.CharField(default='Others', max_length=50)),
                ('availability', models.BooleanField(default=True)),
                ('description', models.CharField(default='', max_length=500)),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
