# Generated by Django 2.2.4 on 2019-09-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letstrydb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
